Css mobile version
assemblee-virtuelle/archipelago pull request #128
Opened 2023-06-23 09:17 UTC by VincentFarcy

Hello,
voici les améliorations css pour la version mobile.
- J'ai dû intervenir sur tous les composants title pour regler un pb de largeur : J'en ai profité pour les mutualiser.
- Le dernier commit est une proposition d'affichage sur 2 lignes de title et actions : beaucoup plus simple à gérer et visuellement correcte de mon point de vue.

2023-06-26 09:16 UTC, srosset81 requested changes
Merci ! Ta proposition de dissocier title et actions me convient bien.
En revanche quelques petits problèmes:
- Pour le header, j'avais dit de mettre à droite, mais c'était juste pour la partie "Reload" et "Utilisateur" (comme sur le design standard de React-Admin https://marmelab.com/react-admin-demo/#/)
- Lorsqu'on affiche un formulaire, le bas de la page n'est pas complètement visible car il y a le bouton "Enregistrer" qui passe par dessus. Il faudrait juste ajouter une marge supplémentaire en bas.
- A mon avis le padding est trop important pour du mobile. 16px pour le cadre extérieur, plus 16px pour le cadre intérieur, ça fait 64px de perdu en largeur. Sur un écran de 320px, ça fait 20% de l'espace qui est inutilisé. Je réduirais à 12px or 8px.

2023-06-26 09:21 UTC, srosset81 commented
Ah j'avais pas vu que la dissociation titre/action était aussi sur desktop. Un peu bizarre là, car du coup les actions semblent très éloignés du contenu, et on ne capte pas forcément qu'ils sont en lien avec. Par exemple le bouton "Editer".

2023-06-26 10:35 UTC, VincentFarcy commented
> Ah j'avais pas vu que la dissociation titre/action était aussi sur desktop. Un peu bizarre là, car du coup les actions semblent très éloignés du contenu, et on ne capte pas forcément qu'ils sont en lien avec. Par exemple le bouton "Editer".


En fait c'était déjà dissocié en mobile.
Le pb en desktop c'est la gestion des longs titres.
Mais on peut annuler le commit si tu préfères.

2023-06-26 10:36 UTC, VincentFarcy commented
Hello, j'ai push les modifs demandées

2023-06-28 07:10 UTC, srosset81 commented
Merci !
Je veux bien que tu revert le commit afin que le titre en desktop soit à nouveau au même niveau que le actions.
Je crois que la plupart des titres entreront sans problème. On pourra éventuellement mettre une limite au nombre de caractères.

2023-06-28 07:31 UTC, VincentFarcy commented
Salut, c'est fait !

2023-06-28 14:19 UTC, merged