Adding Tree function to Topic
assemblee-virtuelle/archipelago pull request #134
Opened 2023-09-25 14:55 UTC by BastienSig

Rajout des thèmes arborescent première. @simonLouvet 
Ici gestion de la liste des thèmes en arborescence, ajout du thème parents dans un thèmes enfant, ajout d'un thème dans une ressource en arborescence.

2023-09-26 10:13 UTC, simonLouvet requested changes

2023-09-26 10:13 UTC, simonLouvet commented on frontend/src/common/ReferenceFilterTree.js
> +  const handleSelect = (event, nodes) => {
ajouter des commentaires pour expliquer le problème de la déselection et le contournement

2023-09-26 10:13 UTC, simonLouvet commented on frontend/src/common/ReferenceFilterTree.js
> +        multiSelect
expliquer que on est multiselect pour pouvoir déclencher le handler (si c'est bien la raison)

2023-09-26 10:13 UTC, simonLouvet commented on frontend/src/common/input/TreeComponent/TreeAutocompleteArrayInput.js
> +const useStyles = makeStyles(theme => ({
je crois que ce n'est plus la bonne méthode en mui 5

2023-09-26 10:13 UTC, simonLouvet commented on frontend/src/common/input/TreeComponent/TreeAutocompleteInput.js
> +const useStyles = makeStyles(theme => ({
mui5

2023-09-26 10:13 UTC, simonLouvet commented on frontend/src/common/list/TreeList.js
> +    redirect('/Theme/'+encodeURIComponent(nodes.id));
Theme en dur; doit être paramétré

2023-10-02 15:53 UTC, simonLouvet requested changes

2023-10-02 15:53 UTC, simonLouvet commented on frontend/package.json
> +    "@mui/x-tree-view": "^6.0.0-alpha.4",
les differntes lib mui devrait être de la même version pour éviter d'avoir des conflit et de telecharger plusieurs fois le mm code source. cela doit être également la même version qu'utilise react-admin si possible.

2023-10-02 15:53 UTC, simonLouvet commented on frontend/src/common/ReferenceFilterTree.js
> +    <div>
pourquoi un div englobante?

2023-10-02 15:53 UTC, simonLouvet commented on frontend/src/common/ReferenceFilterTree.js
> +  * We utilize the `onNodeSelect` function to mimic a click on a single node.
we use

2023-10-02 15:53 UTC, simonLouvet commented on frontend/src/common/input/TreeComponent/TreeAutocompleteInput.js
> +                    className={useStyles.treeStyle}
pas de treeStyle dans la variable useStyles

2023-10-02 15:53 UTC, simonLouvet commented on frontend/src/common/input/TreeComponent/TreeAutocompleteInput.js
> +                <StyledEditIcon className={useStyles.editIcon} onClick={handleOpen} />
pas de pas de editIcon dans la variable useStyles

2023-10-02 17:01 UTC, BastienSig commented on frontend/src/common/ReferenceFilterTree.js
> +    <div>
aucune raison

2023-10-03 08:59 UTC, simonLouvet requested changes

2023-10-03 08:59 UTC, simonLouvet commented on frontend/src/resources/Concept/Theme/ThemeList.js
> +  <List perPage={1000} {...props}>
pourquoi ajouter le perPAge?

2023-10-03 09:03 UTC, simonLouvet approved these changes

2023-10-04 07:34 UTC, BastienSig commented on frontend/src/common/input/TreeComponent/TreeAutocompleteArrayInput.js
> +const useStyles = makeStyles(theme => ({
En effet

2023-10-04 07:34 UTC, BastienSig commented on frontend/src/common/input/TreeComponent/TreeAutocompleteInput.js
> +const useStyles = makeStyles(theme => ({
Modifié

2023-10-04 07:34 UTC, BastienSig commented on frontend/src/common/list/TreeList.js
> +    redirect('/Theme/'+encodeURIComponent(nodes.id));
Je m'en suis occupé

2023-10-04 07:39 UTC, BastienSig commented on frontend/package.json
> +    "@mui/x-tree-view": "^6.0.0-alpha.4",
Mui a eu une update sur ses composants avancé, en v6. Il faut utilisé mui x maintenant et c'est totalement indépendant de mui/core style etc ... qui est resté en v5
Par contre j'ai supprimé mui/lab qui ai devenu obsolète et que j'avais oublié d'enlevé.

2023-10-04 07:39 UTC, BastienSig commented on frontend/src/common/ReferenceFilterTree.js
> +  * We utilize the `onNodeSelect` function to mimic a click on a single node.
Fait

2023-10-04 07:39 UTC, BastienSig commented on frontend/src/common/input/TreeComponent/TreeAutocompleteInput.js
> +                    className={useStyles.treeStyle}
Oui un oublie de ma part, j'ai modifié

2023-10-04 07:39 UTC, BastienSig commented on frontend/src/common/input/TreeComponent/TreeAutocompleteInput.js
> +                <StyledEditIcon className={useStyles.editIcon} onClick={handleOpen} />
Oui un oublie de ma part, j'ai modifié

2023-10-04 07:40 UTC, BastienSig commented on frontend/src/resources/Concept/Theme/ThemeList.js
> +  <List perPage={1000} {...props}>
J'avais un bug sur l'ancienne version de TreeView et TreeItem avec la liste sans perPage mais il semble que ce soit résolue avec la nouvelle version de mui/x donc je l'ai retiré

2023-10-04 22:20 UTC, mguihal reviewed
Je ne bloque pas s'il y a nécessité de merger cette feature, mais il y a plein de petits détails qui me dérangent. Est-ce qu'il est prévu de repasser dessus pour en faire une fonctionnalité plus aboutie ?

D'une manière générale, je ne suis pas fan du double input (autocomplete + modal avec treeView) lors de la sélection du thème ou du parent, c'est confus pour l'utilisateur. On pourrait utiliser un composant comme https://github.com/mikepricedev/mui-tree-select ou https://github.com/dowjones/react-dropdown-tree-select qui font directement le job.

2023-10-04 22:20 UTC, mguihal commented on frontend/src/common/input/TreeComponent/TreeItemUtils.js
> +                        // key={route["id"]} style={route["selected"] ? {color: "#026a63" } : null }
Pourquoi avoir commenté cette ligne ? La key est obligatoire vu qu'on génère un tableau de composants, et ça génère une erreur en console

2023-10-04 22:20 UTC, mguihal commented on frontend/src/common/input/TreeComponent/TreeAutocompleteInput.js
> +  backgroundColor: "#026a63",
C'est possible d'utiliser une couleur issue du thème pour ce composant ?

2023-10-04 22:20 UTC, mguihal commented on frontend/src/common/input/TreeComponent/TreeAutocompleteInput.js
> +  color: "white",
ici aussi, tu peux utiliser une couleur du thème (préférablement la valeur de contrastText de la couleur choisie pour le background)

2023-10-05 08:07 UTC, srosset81 commented
> On pourrait utiliser un composant comme https://github.com/mikepricedev/mui-tree-select ou https://github.com/dowjones/react-dropdown-tree-select qui font directement le job.

L'UX de https://github.com/mikepricedev/mui-tree-select est intéressante, ça vaudrait la peine d'essayer avec des cas concrets, surtout si le composant peut être utilisé tel quel. Par contre je me demande si https://github.com/dowjones/react-dropdown-tree-select fonctionnerait bien en mobile. A tester...

2023-10-05 08:13 UTC, BastienSig commented on frontend/src/common/input/TreeComponent/TreeItemUtils.js
> +                        // key={route["id"]} style={route["selected"] ? {color: "#026a63" } : null }
++ coquille de ma part pour le coup

2023-10-05 08:15 UTC, BastienSig commented
> Je ne bloque pas s'il y a nécessité de merger cette feature, mais il y a plein de petits détails qui me dérangent. Est-ce qu'il est prévu de repasser dessus pour en faire une fonctionnalité plus aboutie ?
> 
> D'une manière générale, je ne suis pas fan du double input (autocomplete + modal avec treeView) lors de la sélection du thème ou du parent, c'est confus pour l'utilisateur. On pourrait utiliser un composant comme https://github.com/mikepricedev/mui-tree-select ou https://github.com/dowjones/react-dropdown-tree-select qui font directement le job.

Je vais faire un test avec mui-tree-select voir ce que ça donne =)

2023-10-26 13:39 UTC, BastienSig commented
J'ai fais une nouvelle update avec le composant https://github.com/mikepricedev/mui-tree-select proposé par @mguihal. Il reste peut être des coquilles que je n'ai pas vue. 
Mais ça fonctionne bien, Simon m'a aidé a modifié un peut le comportement du composant pour pouvoir sélectionner les parents et non que les enfants.

@srosset81 @simonLouvet

2023-10-26 14:00 UTC, srosset81 commented on frontend/src/common/list/TreeList.js
> +    redirect('/'+reference+'/'+encodeURIComponent(nodes.id));
You should use `useCreatePath` as mentionned here: https://marmelab.com/react-admin/Routing.html#linking-to-a-page

2023-10-26 14:00 UTC, srosset81 commented on frontend/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +import CustomTreeSelectArrayInput from '../../../../common/input/TreeComponent/CustomTreeselectArrayInput';
CustomTreeselectArrayInput.js should be renamed CustomTreeSelectArrayInput.js

2023-10-26 14:01 UTC, srosset81 commented on frontend/src/resources/Concept/Theme/ThemeEdit.js
> +            </ReferenceInput> */}
Delete ?

2023-10-26 14:01 UTC, srosset81 commented on frontend/src/common/input/TreeComponent/old/TreeAutocompleteInput.js
> +// import { AutocompleteInput, useGetList, useInput } from "react-admin";
Delete old files (they can still be found with git if needed)

2023-10-26 16:21 UTC, srosset81 approved these changes

2023-10-26 16:23 UTC, srosset81 commented
@BastienSig Pour des nouveaux composants comme ça, ce serait chouette d'inclure une vidéo dans la description de la PR, ça évite d'avoir à tout lancer en local et on peut quand même donner un feedback en fonction du résultat.

2023-10-27 20:21 UTC, mguihal approved these changes
Ok pour moi,
J'ai juste repéré un petit bug quand on édite un thème et qu'on choisit comme parent un thème déjà enfant d'une autre thème, on peut avoir un affichage comme ça : 
<img width="503" alt="Capture d’écran 2023-10-27 à 21 29 58" src="https://github.com/assemblee-virtuelle/archipelago/assets/9048062/a568aa87-df49-4c06-96b6-a1dbe94b6c57">

Et, peut-être qu'on peut ajouter un placeholder sur le champ pour indiquer à quoi il correspond ? (c'est-à-dire un thème sur la vue d'édition d'une organisation, et le thème parent sur la vue d'édition d'un thème)
<img width="395" alt="Capture d’écran 2023-10-27 à 22 19 15" src="https://github.com/assemblee-virtuelle/archipelago/assets/9048062/e48be189-a629-43d9-88d7-ab52ab676fdd">

<img width="500" alt="Capture d’écran 2023-10-27 à 21 28 53" src="https://github.com/assemblee-virtuelle/archipelago/assets/9048062/e57427e7-8887-479d-b2ae-42b8792e43ba">

2023-11-03 10:36 UTC, merged