[Minor] Improve event creation/edition
assemblee-virtuelle/archipelago pull request #137
Opened 2023-10-08 21:09 UTC by mguihal

Hello,

Je propose dans cette PR une amélioration de l'ergonomie de l'interface de création et d'édition des évènements.

**Tensions :** 
- Actuellement via la double page du formulaire de création d'évènement, on peut créer un évènement sans date, qui est introuvable ensuite via l'interface.
- Il n'y a aucune contrainte dans les dates des évènements (ex: on peut mettre une date de fin antérieure à la date de début)
- Il est impossible de rajouter une image (ex: affiche) rattachée à un évènement
- L'ergonomie est trompeuse avec le formulaire de création : Les utilisateurs ne comprennent pas pourquoi indiquer le nom seul avant d'arriver à la suite du formulaire
- L'ergonomie est trompeuse avec le formulaire d'édition à deux onglets : Les utilisateurs ne voient pas naturellement le second onglet

**Propositions de solutions :**
- Fusion du formulaire de création/édition en une seule page et onglet. Création de catégories pour différencier les champs obligatoires et optionnels (Informations de base, Description, Autres informations)

<img width="836" alt="Capture d’écran 2023-10-08 à 22 58 23" src="https://github.com/assemblee-virtuelle/archipelago/assets/9048062/e17e3e87-f014-40b4-8044-d02bc5055d9f">

- Guidage de l'utilisateur en ajoutant des textes de description sur les champs

- Ajout de contraintes sur les deux champs de date pour ne pas pouvoir saisir un évènement avec une date dans le passé, ni de mettre une date de fin antérieure à la date de début. La date de début est maintenant obligatoire.

<img width="657" alt="Capture d’écran 2023-10-08 à 23 01 45" src="https://github.com/assemblee-virtuelle/archipelago/assets/9048062/7c3dca80-0ba3-41a7-b302-28607b0cde08">
<img width="554" alt="Capture d’écran 2023-10-08 à 23 02 05" src="https://github.com/assemblee-virtuelle/archipelago/assets/9048062/825e5dd8-eb97-40db-a7f8-c2801f079d1e">

- Ajout d'un champ d'upload d'image au formulaire

2023-10-09 08:18 UTC, GuillaumeAV commented
Génial !! Merci beaucoup @mguihal !

2023-10-09 08:37 UTC, srosset81 approved these changes
Ca fait un moment que @fluidlog poussait aussi pour ce changement, ça pourrait valoir la peine de le généraliser sur toutes les ressources. Par contre je m'interroge sur le fait qu'on perde la possibilité d'importer un événement externe... il y a peut-être un moyen de proposer un autre élément UX pour ça ?

2023-10-09 08:37 UTC, srosset81 commented on frontend/src/resources/Agent/Activity/Event/index.js
> +    create: EventCreate,
Du coup on perd la possibilité d'importer un événement ?

2023-10-09 21:40 UTC, mguihal commented on frontend/src/resources/Agent/Activity/Event/index.js
> +    create: EventCreate,
Effectivement !

On pourrait envisager de remettre un layout en deux onglets pour le formulaire de création seulement, avec le second pour onglet pour importer un évènement distant.

Cependant, je m'interroge sur l'utilité de la fonctionnalité : 
- Lors de l'utilisation par des personnes lambda, elles ne comprennent pas l'utilité ni le fonctionnement de ce système d'import, et ça les perturbe dans leur expérience de création d'évènement (dans le cas ici). D'autant plus que l'interface actuelle utilise des notions complexes (fork, etc.) qui ne sont pas compréhensibles sans comprendre tout le concept technique d'archipels et d'interopérabilité.

- J'ai encore du mal à voir un cas concret où on voudrait importer un évènement d'une autre instance, mais c'est sûrement dû à ma méconnaissance de l'écosystème Semapps/Archipelago.

- Quand je regarde un exemple comme https://lescheminsdelatransition.org/Event/create qui utilise un frontend qui s'inspire fortement d'Archipelago, il n'y a aucune notion d'import d'évènement non plus.

2023-10-09 22:19 UTC, mguihal commented
Je découvre aussi les nombreuses customisations faites sur le repo des cheminsdelatransition, dont le frontend semble grandement inspiré par Archipelago, sans suivre les dernières avancées mais en apportant beaucoup d'autres améliorations en plus qui n'ont jamais été rapatriées ici, je me pose la question (plus philosophique) du rôle et le but d'Archipelago dans tout ça...

Jusqu'à quel point devons-nous contribuer à ce repo pour l'améliorer ?
Les sites qui s'en servent devraient-il mieux :
 - Forker le repo comme [lescheminsdelatransitions](https://github.com/chemins-de-la-transition/semapps), et continuer de personnaliser comme on a envie chacun de notre côté
 - Surcharger le repo comme fait pour [l'instance de l'AV ](https://github.com/assemblee-virtuelle/deployment_semapps_av) ou [Transiscope Nantes](https://gitlab.com/transiscope-nantes/deploy-archipelago-nantes)

Dans le premier cas, je ne perds pas plus de temps à remonter ici toutes les améliorations/customisations que nous développons pour notre instance, mais ce repo risque de progressivement tomber à l'abandon. Dans le second cas, alors nous devons penser ce repo comme entièrement personnalisable tant dans le contenu, les ressources, le design, etc. de façon à ce qu'il soit prêt clé-en-main à être déployé pour une nouvelle instance...

Je n'ai sans doute pas tout l'historique de pourquoi la création d'Archipelago, quelles sont ses utilisations en prod actuellement, etc., mais ça m'aiderait sûrement à savoir où m'arrêter dans les améliorations que je compte pousser dans ce repo ces prochaines semaines (basées notamment sur notre utilisation de notre instance Transiscope Nantes en conditions réelles).

Je prends pour exemple le contenu de cette PR : 
- Est-ce que l'import d'évènement devrait être quelque chose de personnalisable selon les instances pour savoir si on doit l'afficher ou pas, si cette fonctionnalité est utile pour certaines instances mais pas pour d'autres ?
- Est-ce que si dans le futur on doit rajouter des nouvelles améliorations aux évènements qui peuvent être utiles pour tout le monde, mais qui ne sont pas forcément dans l'ontologie PAIR (exemples possibles au hasard : ajouter un lien vers les organisateurs des évènements, indiquer si l'évènement est en ligne ou pas, s'il est complet ou pas, les lier à une ressource Lieu plus complète qu'une simple adresse, etc.) Est-ce que ça a sa place sur ce repo ou pas ?

2023-10-10 07:33 UTC, srosset81 commented on frontend/src/resources/Agent/Activity/Event/index.js
> +    create: EventCreate,
Pour moi le fait de pouvoir importer une ressource extérieure est une valeur ajoutée fondamentale d'Archipelago par rapport à d'autres solutions. Elle est actuellement peu utilisée, car il y a peu de serveurs interopérables, mais le but c'est que ça change. Et l'UX peut sans doute être améliorée. Mais avec l'onglet ça fonctionnait plutôt bien, un utilisateur débutant n'allait pas trop y faire attention, et un utilisateur avancé pouvait s'amuser avec.

2023-10-10 07:40 UTC, srosset81 commented
> Je découvre aussi les nombreuses customisations faites sur le repo des cheminsdelatransition, dont le frontend semble grandement inspiré par Archipelago, sans suivre les dernières avancées mais en apportant beaucoup d'autres améliorations en plus qui n'ont jamais été rapatriées ici, je me pose la question (plus philosophique) du rôle et le but d'Archipelago dans tout ça...

Je ne vois pas trop quelles fonctionnalités des CDLT te semblent manquer à Archipelago, tu as des exemples ? Pour moi l'instance des CDLT est très spécifique aux besoins de ce projet, alors qu'Archipelago a pour but de proposer une application qui peut être utilisé pour de nombreux projets et collectifs.

> * Est-ce que si dans le futur on doit rajouter des nouvelles améliorations aux évènements qui peuvent être utiles pour tout le monde, mais qui ne sont pas forcément dans l'ontologie PAIR (exemples possibles au hasard : ajouter un lien vers les organisateurs des évènements, indiquer si l'évènement est en ligne ou pas, s'il est complet ou pas, les lier à une ressource Lieu plus complète qu'une simple adresse, etc.) Est-ce que ça a sa place sur ce repo ou pas ?

Le choix jusqu'à maintenant est de dire que Archipelago = ontologie PAIR. Il est tout à fait possible d'étendre l'ontologie PAIR s'il y a des choses qui manquent.

En tout cas ce sont des questions importantes pour lesquelles il n'y a pas de réponses simples. J'ai trop la tête dans ActivityPods en ce moment pour y répondre, mais je crois que @GuillaumeAV serait ravi d'en discuter.

2023-10-10 11:14 UTC, mguihal commented on frontend/src/resources/Agent/Activity/Event/EventForm.js
> +        helperText="Indiquez ici les organisations, groupes ou personnes qui sont impliqués dans l'évènement"
Ici ça me paraîtrait plus logique de mettre "qui organisent l'évènement" ?
Mais la relation `pair:involves` ne semble pas cibler seulement les organisateurs, mais englober aussi les participants, intervenants, etc.
Existe-t'il une relation plus spécifique ?

2023-10-10 12:21 UTC, srosset81 commented on frontend/src/resources/Agent/Activity/Event/EventForm.js
> +        helperText="Indiquez ici les organisations, groupes ou personnes qui sont impliqués dans l'évènement"
On peut utiliser une relation réifiée (involvementActivity/involvementActor). Voir le [diagramme](https://virtual-assembly.org/ontologies/pair-2021-summer/index-en.html). Perso je pense que les relations réifiées sont trop complexes pour ce type de cas très courants, et je serai favorable à un `pair:organizedBy`.

2023-10-10 13:08 UTC, GuillaumeAV commented
Yo ! 

On a un cdlt:organizedBy ... C'est typiquement le genre de choses qu'on devrait transférer du custom cdlt direction le générique pair ! 

On bosse dessus cette semaine et les suivantes avec Damien puis avec Thomas !

2023-10-15 20:32 UTC, mguihal commented on frontend/src/resources/Agent/Activity/Event/index.js
> +    create: EventCreate,
Je propose une solution dans ce commit : https://github.com/assemblee-virtuelle/archipelago/pull/137/commits/ff5c33501810dc915925cef8bc59f660c41cb175

Par défaut la ressource peut être importée et j'ai remis l'onglet dans le formulaire de création.

Mais une configuration dans le thème `archipelago.importableResources` permet de désactiver cet onglet si la ressource n'est pas listée.

2023-10-16 08:23 UTC, srosset81 requested changes

2023-10-16 08:23 UTC, srosset81 commented on frontend/src/config/theme.js
> +  },
Pour moi, le theme devrait se contenter de gérer l'affichage mais pas d'autres types de configurations. Après tout, c'est une config de MUI. C'est sans doute plus adapté dans le fichier config/config.js, sachant que ça pourrait permettre de le définir dans des variables d'env (qui seraient ensuite parsée dans le fichier config.js).

2023-10-16 12:41 UTC, srosset81 approved these changes

2023-10-17 07:54 UTC, merged

2023-10-17 10:23 UTC, fluidlog commented
Merci @mguihal d'apporter ce débat très intéressant. Comme dit @srosset81, je suis passé par là il y a 6 mois, et j'ai fait le même chemin que toi. J'ai observé les CDLT pour m'inspirer et comprendre, et je me suis demandé comment on allait faire évoluer tout ça vers des "produits SemApps" facilement réutilisables... et c'est pas simple.
Pour info, j'en avais fait un PAD : https://pad.lescommuns.org/InstallationCheminsDeLaTransitionEnLocal

Depuis, je fais avec la structure que j'ai décrit dans le schéma ici : https://portal.carto4ch.huma-num.fr/assets/images/toolbox-semapps-48e77414612cbe9062d06f9b62980b56.png
Il y a une boite à outil SemApps avec un middleware, et pleins de frontend, et en fonction du projet, à nous d'aller piocher là où ça nous intéresse, en prenant petit bout par petit bout. Ce n'est en effet pas très efficace, mais c'est comme ça à l'heure actuelle.

Pour mon projet Carto4CH, j'utilise comme toi une base d'Archipelago (je n'ai pas besoin des fonctions supplémentaires de CDLT pour mon projet), et maintenant, je reste autonome dans mon fork d'Archipelago. Je jette régulièrement un oeil sur les nouveautés de archipelago AV, et si elles m'intéressent, je fais des C/C dans mon code, ça me permet de bien comprendre ce que je fais et comment ça fonctionne.

Pour mon futur projet Permalieux, j'hésites encore à partir de CDLT ou de Oasis, mais je verrai ça en 2024...

Pour les **formulaires en une page**, en effet, on est, semble-t-il, tous d'accord pour les utiliser, pour cela, j'ai commencé par m'inspirer de WTMP (Welcome to my place) : 
https://pad.lescommuns.org/FormulaireDeCreationSurUneSeulePage

Puis, plus tard, Seb m'a orienté vers son dernier projet Oasis, et je me suis de nouveau inspiré du code pour faire le mien.
https://pad.lescommuns.org/InstallationAnalyseDuCodeOasis

Pour ce qui est de l'import de page externes, je n'en ai pas le besoin. Je suis OK si c'est paramétrable simplement.

@GuillaumeAV ; je suis intéressé par une réunion sur le sujet, même si je ne serai pas d'une grande aide pour prendre des choix d'architectures stratégiques pour le futur. La situation actuelle me va bien, mais elle demande une lourde montée en compétence, pour connaitre tous les projets, et tous les codes à droite et à gauche. Heureusement qu'on utilise des composants réutilisables qui sont bien documentés, ça permet d'avoir une boite de légos communes.