bugfix when no reified predicat exists
assemblee-virtuelle/archipelago pull request #174
Opened 2024-03-28 19:19 UTC by simonLouvet

resolve #173

2024-03-30 02:28 UTC, mguihal approved these changes

2024-04-01 07:06 UTC, srosset81 requested changes

2024-04-01 07:06 UTC, srosset81 commented on middleware/services/organizations.service.js
> +  mixins: [ControlledContainerMixin, DisassemblyMixin, DereferenceMixin],
Le DereferenceMixin doit aussi être remis sur le users service.

2024-04-04 09:00 UTC, simonLouvet commented on middleware/services/organizations.service.js
> +  mixins: [ControlledContainerMixin, DisassemblyMixin, DereferenceMixin],
exact

2024-04-04 09:05 UTC, merged