[patch] Validate multi-url input
assemblee-virtuelle/archipelago pull request #178
Opened 2024-04-20 21:43 UTC by mguihal

Hello,

Il y a actuellement un bug sur les pages Organisation, quand on met une valeur qui n'est pas une url valide dans le champ "Site web".

J'ai changé le champ : 
- en tableau de champs car visiblement on pouvait auparavant mettre plusieurs sites web pour une organisation, donc un seul input c'est pas l'idéal
- renforcé la validation de l'input avec un type="url" qui fera l'affaire pour l'instant

PR associée sur Semapps pour l'affichage de la page si de telles valeurs sont déjà saisies : https://github.com/assemblee-virtuelle/semapps/pull/1245

2024-04-22 09:21 UTC, srosset81 approved these changes

2024-04-23 09:00 UTC, simonLouvet requested changes

2024-04-23 09:00 UTC, simonLouvet commented on frontend/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +        <ArrayInput source="pair:homePage" fullWidth>
Attention, il me semble que ArrayInput ne supporte que des propriétés qui ne sont pas fournies sous forme de tableau et plantera si la propriété est une String. je connais mal dernières versions de react admin et peut-être que cela a changé.
1/ le user saisie UNE url et sauvegarde
2/ lors de la navigation sur le formulaire d'edit, le dataprovider fournira propriété sous forme d'une string par ce que c'est le standard jsonLD : si un prédicat n'a qu'une valeur, il n'est pas retourné comme un tableau, car il n'y a pas de notion de schéma de donnée qui expliciterait que cette propriété est un tableau.

2 solutions :
- utiliser le paramètre forceArray sur la ressource pour forcer la propriété à être fournie comme un tableau : https://semapps.org/docs/frontend/semantic-data-provider/data-model
- implémenter un ArrayInput Semapps à l'image de  ReferenceArrayInput https://github.com/assemblee-virtuelle/semapps/blob/master/src/frontend/packages/input-components/src/ReferenceArrayInput.js

préférence pour la 2ᵉ solution pour aller dans la direction que prend semapps souhaité par @srosset81

2024-04-23 10:47 UTC, srosset81 commented on frontend/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +        <ArrayInput source="pair:homePage" fullWidth>
Merci, effectivement il faut sans doute un composant ArrayInput custom

2024-04-24 19:56 UTC, mguihal commented on frontend/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +        <ArrayInput source="pair:homePage" fullWidth>
J'arrive à reproduire le souci dont vous parlez en effet.

Quel est le schéma de données derrière pair:homePage ? Je me suis renseigné sur cette page : https://virtual-assembly.org/ontologies/pair-2021-summer/index-en.html#homePage mais ça n'est pas clair, ce n'est pas clairement indiqué si le type de la donnée est un tableau ou une chaine de caractères. Pour moi c'est soit l'un soit l'autre mais on ne peut pas accepter les deux non ?

2024-04-25 18:41 UTC, srosset81 commented on frontend/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +        <ArrayInput source="pair:homePage" fullWidth>
Ca fait partie du format JSON-LD: s'il y a qu'une valeur, c'est une string, sinon c'est un tableau. C'est embêtant à gérer mais pas le choix.

2024-05-06 21:24 UTC, mguihal commented on frontend/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +        <ArrayInput source="pair:homePage" fullWidth>
J'ai ajouté un nouveau composant JsonLDArrayInput qui prend en compte cette spécification du coup. Est-ce que ça conviendrait ?

2024-05-07 09:43 UTC, srosset81 approved these changes

2024-05-07 09:43 UTC, srosset81 commented on frontend/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +        <ArrayInput source="pair:homePage" fullWidth>
Ouais c'est génial ! Merci

2024-05-07 19:51 UTC, simonLouvet approved these changes

2024-07-09 00:10 UTC, mguihal commented on frontend/src/resources/Agent/Actor/Organization/OrganizationEdit.js
> +        <ArrayInput source="pair:homePage" fullWidth>
Je me permets de revenir sur cette PR avec une question, puisque avec du recul, faire transpirer une spécificité du modèle de donnée dans l'interface par la création d'un nouveau composant me dérange un peu tout de même 🫤 

Sur les deux possibilités qu'avait listé @simonLouvet , la première qui était d'utiliser le paramètre `forceArray` dans le dataModel était selon vous une moins bonne solution (elle est d'ailleurs indiqué comme "to be deprecated" dans la doc https://semapps.org/docs/frontend/semantic-data-provider/data-model), mais je me demande pourquoi exactement. En effet, ça fait partie pour moi du rôle du dataProvider de transformer le format de données reçu (JsonLD) en un format de données générique utilisable par React-admin et l'interface, plutôt que de laisser cette logique à cette dernière, et je trouve ça dommage de déprécier cette fonctionnalité (De plus  que le data-provider transforme déjà certaines données, par exemple le "@id" en "id") Je manque peut-être d'historique sur pourquoi c'est une plus mauvaise solution ?

2024-07-26 21:33 UTC, merged